# Jupyter Book config (Chinese)

project:
  name: MindQuantum 文档 (中文)
  description: MindQuantum 教程与 API 文档（中文）

parse:
  myst_enable_extensions:
    - deflist
    - colon_fence
    - dollarmath
    - amsmath
    - linkify

execute:
  execute_notebooks: off

html:
  favicon: ../_static/favicon.svg
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  extra_navbar: |
    <a href="../../" class="mq-home-link">← 返回首页</a> ·
    <a href="../en/" class="mq-home-link">English</a>
  extra_footer: |
    <div class="mq-footer">© {current_year} MindQuantum.</div>

theme:
  name: sphinx_book_theme
  logo: ../_static/favicon.svg
  options:
    navigation_depth: 2
    show_toc_level: 2
    use_download_button: false
    use_fullscreen_button: false

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.napoleon
    - sphinx.ext.mathjax
    - sphinx.ext.viewcode
    - nbsphinx
    - IPython.sphinxext.ipython_console_highlighting
  config:
    language: zh_CN
    html_search_language: zh
    source_suffix:
      .rst: restructuredtext
      .md: markdown
    html_static_path: ["../_static"]
    html_css_files:
      - mq-variables.css
      - mq-theme.css
