# Jupyter Book config (English)

title: MindQuantum Docs (EN)
description: Tutorials and API reference for MindQuantum (English)

parse:
  myst_enable_extensions:
    - deflist
    - colon_fence
    - dollarmath
    - amsmath
    - linkify

execute:
  execute_notebooks: off

html:
  favicon: ../_static/favicon.svg
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  extra_navbar: |
    <a href="../../" class="mq-home-link">← Back to Home</a> ·
    <a href="../zh/" class="mq-home-link">中文</a>
  extra_footer: |
    <div class="mq-footer">© {current_year} MindQuantum.</div>

launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org
  notebook_interface: classic
  repository_url: https://github.com/MindQuantum-HiQ/mq-env
  branch: main

theme:
  name: sphinx_book_theme
  logo: ../_static/favicon.svg
  options:
    navigation_depth: 2
    show_toc_level: 2
    use_download_button: false
    use_fullscreen_button: false

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.napoleon
    - sphinx.ext.mathjax
    - sphinx.ext.viewcode
    - IPython.sphinxext.ipython_console_highlighting
  config:
    language: en
    html_static_path: ["../_static"]
    html_css_files:
      - mq-variables.css
      - mq-theme.css
    thebe_config:
      repository_url: https://github.com/MindQuantum-HiQ/mq-env
      repository_branch: main
      binderhub_url: https://mybinder.org
